//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:50:35 AM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://oldLibrary.com/books", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.oldlibrary.books;
